#! /bin/bash

usage () {
    echo "usage: $(basename $0) [-f file] file" 1>&2
    exit 255
}

list="list"

while getopts 'f:' OPTION
do
    case $OPTION in
    f) list="$OPTARG"
       ;;
    *) usage
       ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
    usage
fi

file=$1

top=$(egrep -v '^(#|$)' $list | head -1)
scp $top:$file $file.$top

for i in $(egrep -v '^(#|$)' $list)
do
    scp $i:$file $file.$i
    diff $file.$top $file.$i
    rm -f $file.$i
done

rm -f $file.$top

exit 0
